#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';
use AramHamo\Mvc\Schema;
function help(){
  echo "Usage:\n\n";
  echo "serve         launch a local dev server\n";
  echo "migrate       migrate\n";
}
function migrate(){
  $tables = glob("migrations/*.php");
  foreach($tables as $table){
    include $table;
    echo "Creating ". $GLOBALS['tableName']."\n";
    $table::up();
  }
}
function drop($tableName){
  $schema = new Schema;
  $schema->dropIfExists($tableName);
}
if($argc < 2){
  help();

}elseif($argv[1] == "serve"){
  shell_exec("php -S 0.0.0.0:8080 -t public");

}elseif($argv[1] == "migrate"){
  migrate();
}elseif($argv[1] == "drop"){
  $table = $argv[2];
  drop($table);
}else{
  help();

}
