#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';
require '.config.php';
use AramHamo\Mvc\Schema;
function help(){
echo "Usage:\n
\033[32mserve             \033[0mlaunch a local dev server
\033[32mmigrate           \033[0mmigrate all
\033[32mmigrate \033[0m<table>   migrate a specific table
\033[32mdropall           \033[0mdrop all tables
\033[32mdrop \033[0m<table>      drop a specific table\n";
}
function migrate(){
if(CONFIG["DATABASE"]["SOFTWARE"] == "sqlite"){
  if(!extension_loaded("pdo_sqlite")){
    echo "\033[31mError: \033[0mpdo_sqlite module not loaded\n";
    exit;
  }
}else if(CONFIG["DATABASE"]["SOFTWARE"] == "mysql"){
  if(!extension_loaded("pdo_mysql")){
    echo "\033[31mError: \033[0mpdo_mysql module not loaded\n";
    exit;
  }
}
  $tables = glob("migrations/*.php");
  foreach($tables as $table){
    include $table;
    echo "\033[32mCreating \033[0m". $GLOBALS['tableName']."\n";
    $table::up();
  }
}
function drop($tableName){
  $schema = new Schema;
  $schema->dropIfExists($tableName);
  echo "\033[32mDeleting \033[0m". $tableName."\n";
}
function dropall(){
  $schema = new Schema;
  $tables = glob("migrations/*.php");
  foreach($tables as $table){
    include $table;
    $schema->dropIfExists($GLOBALS["tableName"]);
    echo "\033[32mDeleting \033[0m". $GLOBALS["tableName"]."\n";
  }
}
function newPage($pageName){
  $controllerTemplate = '<?php declare(strict_types=1);
  namespace AramHamo\Mvc\Controllers;
  use AramHamo\Mvc\View;

  class '.ucfirst($pageName).'{
    public function get(){
      return View::render("'.strtolower($pageName).'",array("title"=>"'.$pageName.'"));
    }
    public function post(){
    }
    public function update(){
    }
    public function delete(){
    }
  }';
  $fController = fopen("Mvc/Controllers/".ucfirst($pageName.".php"),"w");
  fwrite($fController,$controllerTemplate);
}
if($argc < 2){
  help();

}elseif($argv[1] == "serve"){
  shell_exec("php -S 0.0.0.0:8080 -t public");

}elseif($argv[1] == "migrate"){
  migrate();

}elseif($argv[1] == "drop"){
  if(isset($argv[2])){
    drop($argv[2]);
  }

}elseif($argv[1] == "dropall"){
    dropall();

}elseif($argv[1] == "newpage"){
    newPage($argv[2]);

}else{
  help();

}
